services:
  api:
    build:
      context: ./api
    container_name: express_api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/firestore_schemas
    depends_on:
      - mongo

  app:
    build:
      context: ./app
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_ENCRYPTION_KEY = 1234567890abcdef
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
