services:
  fireresty:
    container_name: fireresty
    image: tobiaslozano/fireresty:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodbURL
    volumes:
      - /path/to/storage:/data
    restart: unless-stopped

volumes:
  mongo_data:
